# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 89c1b6bd0db42283590a5ae8254e68c57e8ad6070b9d749048aa0e6ef984d846d71e4a1a5b46db1a325cd25962114c41aa7255e32f3a645637ab0386bd66fda4

test:
  secret_key_base: 6b380bdbf23f6d39ac757164695bf37ad7cc2c33a1e41c72590a7039e1df3d729cc6d6962abda9cf5e0baf18f7ba6ac8daf79523554d5482bd8d5e0a49c3d478

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
